### ISSUE TITLE
Official deployment: checklist

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#180]
In order to launch our new Website numerous tasks have to be done (incomplete):

- [x] Remove hardcoded paths in (remove `staging.`):
    - https://github.com/OSGeo/grass-website/blob/a8c3e8dc0769cb0707f8651f08f4e239c7f4af4e/config.toml#L1
    - https://github.com/OSGeo/grass-website/blob/a8c3e8dc0769cb0707f8651f08f4e239c7f4af4e/config.toml#L234
    - responsible: @neteler 
    - done in e6dfabd6a5deaf7678f28ed1115958b5e1eb7c98
- [x] Switch DNS:
    - grass.osgeo.org --> old.grass.osgeo.org
    - staging.grass.osgeo.org --> grass.osgeo.org
    - see https://trac.osgeo.org/osgeo/ticket/2485
    - responsible: @neteler, OSGeo-SAC (Regina)
- [x] Move CMSMS to different domain:
    - http://old.grass.osgeo.org/
    - clear cache
    - change urls in
        - `/var/www/grass/grass-cms/config.php`
        - `/var/www/grass/grass-cms/.htaccess`
        - elsewhere: `neteler@osgeo6:/var/www/grass/grass-cms$ sudo find . -type f | xargs grep grass.osgeo.org | grep -v 'tmp\|manuals\|announces\|binary\|source\|newsletter\|programming\|uploads\|grass[3-7]'`
    - clear cache again
    - double check `config.php` for path/url
    - hope we never used absolute url's in templates/style sheets...
    - check the cms mailer and/or other mailing modules
    - responsible: @neteler
- [x] disable cronjob on osgeo6:
    - responsible: @neteler
- [x] transfer Apache redirects from osgeo6 to osgeo7:
    - `neteler@osgeo6:~$ sudo vim /etc/apache2/includes/grass.osgeo.org.inc`
    - carefully copy over and update redirects as needed
    - responsible: @neteler
- [x] Test new and old website:
    - all functional after the DNS switch: both hugo and CMSMS site?
        - https://old.grass.osgeo.org/
        - https://grass.osgeo.org/
    - responsible: **tbd**
- [x] Check if links in the Wiki still point correctly
    - add redirects as needed in apache config, or, update Wiki
    - around 60 redirects added
    - responsible: @neteler
- [x] write press release: see #198
    - short "sightseeing" tour in the new website
    - Mention Nicolas Bozon <nicolas.bozon@gmail.com> as the main designer (@nbozon)
    - also advertise: mailing lists, wiki, github repos
    - responsible: @veroandreo 
- [x] publish press release: see #198
   - on 29 July 2020, the GRASS GIS birthday!
    - responsible: @neteler
- [x] Notify the mirror server operators about new URL:
    - see #181
    - responsible: @neteler
- [x] Mention mirror list on main page
    - see #207
    - see  #209 for howto mirror
    - responsible: @mlennert 
- [x] Check if backup of grasslxd is running:
    - LXD container on osgeo7, via OSGeo-SAC: http://wiki.osgeo.org/wiki/SAC:Backups
    - responsible: @neteler, OSGeo-SAC (Regina)
- [x] update RSS feed on https://planet.osgeo.org:
    - old: https://grass.osgeo.org/feeds/Mainpage.rss
    - new: https://grass.osgeo.org/index.xml
    - https://trac.osgeo.org/osgeo/ticket/2486
    - responsible: @neteler -> jsanz (?)
- [x] Check if snapshot compilation is running:
    - src, binary snapshots, manuals, progman, addons
        - https://grass.osgeo.org/grass78/manuals/ | https://grass.osgeo.org/grass79/manuals/
        - https://grass.osgeo.org/grass78/binary/linux/snapshot/ | https://grass.osgeo.org/grass79/binary/linux/snapshot/
        - https://grass.osgeo.org/grass7/manuals/addons/ (check date)
        - https://grass.osgeo.org/programming7/ (check date)
    - responsible: @neteler, @landam
- [x] Check if i18N translation statistics are generated:
    - i18N translation statistics (currently https://grass.osgeo.org/development/translations/#statistics)
        - https://grass.osgeo.org/uploads/grass/
    - generated via cronjob at https://grass.osgeo.org/grass79/binary/linux/snapshot/
    - also used in the wxGUI
    - responsible: @neteler
- [x] Remove from cronjob to package for old osgeo6 server
   - edit: https://github.com/OSGeo/grass-addons/blob/b1d3144e2f597b3dff7f6fba0b831ea6d24eb7d9/tools/cronjobs_osgeo_lxd/cron_job_list_grass#L32
    - responsible: @neteler
- [x] Check if all is ok in the search engines, _after_ the DNS change:
    - Google indexing: https://search.google.com/search-console?resource_id=http%3A%2F%2Fgrass.osgeo.org%2F
    - Bing indexing: https://www.bing.com/webmasters?siteUrl=https://grass.osgeo.org/
    - responsible: @neteler

(edit this list for more TODOs)

**Comment by neteler** [comment]
Planned date for DNS switch: 27 July 2020 - @neteler + Regina Obe

**Comment by neteler** [comment]
We are in good shape :-)

**Comment by neteler** [comment]
All done, happily closing.

Special thanks to [Regina Obe](https://wiki.osgeo.org/wiki/User:Robe) from SAC for her continuous support with `grasslxd`, DNS and SSL certificates. And also to all initial release [contributors](https://github.com/OSGeo/grass-website/graphs/contributors)!
